f = input("First => ")
print(f)
s = input("Second => ")
print(s)
print("Example variable names")
lc = f.lower()+"_"+s.lower()
print("Lower case:",lc,len(lc))
fc = f.upper()+"_"+s.upper()
print("For constants:",fc,len(fc))
cc = f.capitalize()+s.capitalize()
print("Camel case:",cc,len(cc))
sv = "_"+f.lower()+"_"+s.lower()
print("System variables:",sv,len(sv))
n = f.lower()+"_"+s.lower()
rl = n.replace("l","_")
ro = rl.replace("o","_")
print("Silly variable:",ro)