rs= int(input("Enter the radius of the Sun (miles) -> "))
print(rs)
rm= int(input("Enter the radius of the Moon (miles) -> "))
print(rm)
ds= int(input("Enter the maximum distance to the Sun (miles) -> "))
print(ds)
dm= int(input("Enter the minimum distance to the Moon (miles) -> "))
print(dm)
rma= float(input("Enter the rate the Moon is moving away (in/year) -> "))
print(rma)
dme= float(ds*(rm/rs))
print("The Moon will have exactly the same apparent size as the Sun when it is {:.2f}".format(dme),"miles away.")
r= float(dme-dm)
print("The Moon will need to recede another {:.2f}".format(r),"miles")
t= int(float(r/((rma/12)/5280)))
print("Which will occur in",t,"years at the current rate.")